system:
  addr: ":8080"
  grpc: "0.0.0.0:5678"
  logfile: "log.txt"
  serct: "123456"
  client_port: "8010"
  database:
    mysqlhost: "localhost"
    mysqlport: "3306"
    mysqluser: "root"
    mysqlpassword: "166490"
    mysqldatabasename: "bigagent"
