system:
  addr: ":8080"
  grpc: "192.168.0.83:5678"
  logfile: "log.txt"
  database:
    mysqlhost: "localhost"
    mysqlport: "3306"
    mysqluser: "root"
    mysqlpassword: "166490"
    mysqldatabasename: "bigagent"
